-- ClanBridge — all applicable migrations, in order, as one transaction.
--
-- GENERATED by `npm run migrations:bundle`. Do not edit; edit the files in
-- supabase/migrations/ instead.
--
-- Paste this whole file into the Supabase SQL editor and run it once.
-- BEGIN/COMMIT means a failure anywhere rolls the entire thing back, so you
-- cannot end up with a half-applied schema.
--
-- Includes: 001_core.sql, 002_cwl.sql, 003_war.sql, 004_features.sql, 005_operational.sql, 006_rls.sql, 007_member_snapshots.sql, 008_player_left_at.sql, 013_user_status.sql, 014_service_role_grants.sql, 015_platform_admin.sql, 016_player_verification.sql, 017_approval_grants_membership.sql, 018_admin_may_approve_clanless.sql, 019_cwl_war_members.sql
--
-- Deliberately EXCLUDED: 010_polls, 011_cwl_rosters, 012_war_lineups. Those
-- are still comment-only stubs for Phase 4B and T6.8. 009 does not exist.

begin;

-- ========================================================================
-- 001_core.sql
-- ========================================================================

-- T1.4 — Core tables: clans, users, players, clan_roles.
--
-- Apply in the Supabase SQL editor, in numeric order. Once applied, never edit
-- this file — fix forward with a new migration (section 4).
--
-- Conventions: snake_case, plural names, uuid primary keys, created_at on every
-- table, deleted_at on every table (R4 — nothing is ever deleted).

-- ---------------------------------------------------------------------------
-- Shared helper: keep updated_at honest without relying on every caller.
-- ---------------------------------------------------------------------------
create or replace function set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;


-- ---------------------------------------------------------------------------
-- clans — the three clans. Seeded by supabase/seed.sql (T1.10).
-- ---------------------------------------------------------------------------
create table clans (
  id          uuid primary key default gen_random_uuid(),
  tag         text not null unique,
  name        text not null,
  badge_url   text,
  is_active   boolean not null default true,
  created_at  timestamptz not null default now(),
  updated_at  timestamptz,
  deleted_at  timestamptz,

  -- Section 4: tags are stored with the hash and uppercased on write.
  -- Enforced here so a bad write fails loudly instead of producing a 404 later.
  --
  -- The pattern is Supercell's actual tag alphabet. Note the characters that are
  -- absent: I, O, S and most digits. Checking only case and the leading hash
  -- would accept '#REPLACE1', which lib/tags.ts rejects — the database and the
  -- parser must agree, or a placeholder survives into production.
  constraint clans_tag_format check (tag ~ '^#[0289PYLQGRJCUV]{3,12}$')
);

create trigger clans_set_updated_at
  before update on clans
  for each row execute function set_updated_at();


-- ---------------------------------------------------------------------------
-- users — application profile, one per Supabase auth user.
--
-- Architecture.md 7.1 puts the auth user above the profile, so id IS the auth
-- user id rather than a separate key. on delete restrict, never cascade: R4
-- means a row is never removed as a side effect of something else.
-- ---------------------------------------------------------------------------
create table users (
  id            uuid primary key references auth.users (id) on delete restrict,
  email         text not null,
  display_name  text,
  created_at    timestamptz not null default now(),
  updated_at    timestamptz,
  deleted_at    timestamptz
);

create trigger users_set_updated_at
  before update on users
  for each row execute function set_updated_at();


-- ---------------------------------------------------------------------------
-- players — one row per Clash of Clans account.
--
-- Written by scripts/sync/clans.ts from the clan member list (R11: game fact).
-- user_id is NULLABLE and stays null until the player verifies at T3.3 — sync
-- creates these rows long before anyone claims them.
-- ---------------------------------------------------------------------------
create table players (
  id            uuid primary key default gen_random_uuid(),
  clan_id       uuid references clans (id) on delete restrict,
  user_id       uuid references users (id) on delete restrict,
  tag           text not null unique,          -- T1.4: the idempotency key for sync
  name          text not null,
  th_level      smallint,
  verified      boolean not null default false,
  -- NOT named current_role: that is a reserved keyword in PostgreSQL and the
  -- create table fails outright with a syntax error. proposal_idea.md section
  -- 10.1 sketches it as current_role; this is the corrected name.
  clan_role     text check (clan_role in ('leader', 'co-leader', 'elder', 'member')),
  created_at    timestamptz not null default now(),
  updated_at    timestamptz,
  deleted_at    timestamptz,

  -- Supercell's tag alphabet, not merely "uppercase with a hash". This rejects
  -- a tag containing the letter O, which is the most common transcription error
  -- and would otherwise sit in the database producing 404s against the API.
  constraint players_tag_format check (tag ~ '^#[0289PYLQGRJCUV]{3,12}$')
);

create trigger players_set_updated_at
  before update on players
  for each row execute function set_updated_at();

-- Partial indexes: every read filters deleted_at is null, so the dead rows are
-- not worth indexing.
create index players_clan_id_idx on players (clan_id) where deleted_at is null;
create index players_user_id_idx on players (user_id) where deleted_at is null;


-- ---------------------------------------------------------------------------
-- clan_roles — a user's role within one clan.
--
-- Roles are PER CLAN, not global: co-leader of clan A is an ordinary member of
-- clan B. This table is also what auth_clan_ids() reads in 006_rls.sql, which
-- makes it the root of the whole authorisation model.
-- ---------------------------------------------------------------------------
create table clan_roles (
  id          uuid primary key default gen_random_uuid(),
  user_id     uuid not null references users (id) on delete restrict,
  clan_id     uuid not null references clans (id) on delete restrict,
  role        text not null check (role in ('leader', 'co-leader', 'elder', 'member')),
  created_at  timestamptz not null default now(),
  updated_at  timestamptz,
  deleted_at  timestamptz,

  unique (user_id, clan_id)
);

create trigger clan_roles_set_updated_at
  before update on clan_roles
  for each row execute function set_updated_at();

create index clan_roles_user_id_idx on clan_roles (user_id) where deleted_at is null;
create index clan_roles_clan_id_idx on clan_roles (clan_id) where deleted_at is null;

-- ========================================================================
-- 002_cwl.sql
-- ========================================================================

-- T1.5 — Clan War League tables.
--
-- This is the data the whole project exists to capture. Supercell deletes CWL
-- data when the season ends and it cannot ever be re-fetched, so every table
-- here is append-only in practice (R5) and never hard-deleted (R4).

-- ---------------------------------------------------------------------------
-- cwl_seasons — one row per clan per monthly league season.
-- ---------------------------------------------------------------------------
create table cwl_seasons (
  id          uuid primary key default gen_random_uuid(),
  clan_id     uuid not null references clans (id) on delete restrict,
  season      text not null,                  -- 'YYYY-MM', as the API reports it
  league      text,
  created_at  timestamptz not null default now(),
  updated_at  timestamptz,
  deleted_at  timestamptz,

  -- Natural key. Re-running the sync finds this row instead of making a second.
  unique (clan_id, season)
);

create trigger cwl_seasons_set_updated_at
  before update on cwl_seasons
  for each row execute function set_updated_at();


-- ---------------------------------------------------------------------------
-- cwl_wars — one war day within a season.
--
-- war_tag is Supercell's own identifier and the real idempotency key: the same
-- war appears under the same tag on every poll for the whole week.
-- ---------------------------------------------------------------------------
create table cwl_wars (
  id                  uuid primary key default gen_random_uuid(),
  season_id           uuid not null references cwl_seasons (id) on delete restrict,
  war_tag             text not null unique,
  day_number          smallint,
  opponent_tag        text,
  opponent_name       text,
  team_size           smallint,
  state               text check (state in ('preparation', 'inWar', 'warEnded')),
  our_stars           smallint,
  their_stars         smallint,
  our_destruction     numeric(5, 2),
  their_destruction   numeric(5, 2),
  result              text check (result in ('win', 'lose', 'tie')),
  start_time          timestamptz,
  end_time            timestamptz,
  created_at          timestamptz not null default now(),
  updated_at          timestamptz,
  deleted_at          timestamptz,

  constraint cwl_wars_tag_format check (war_tag = upper(war_tag) and war_tag like '#%')
);

create trigger cwl_wars_set_updated_at
  before update on cwl_wars
  for each row execute function set_updated_at();

create index cwl_wars_season_id_idx on cwl_wars (season_id) where deleted_at is null;


-- ---------------------------------------------------------------------------
-- cwl_attacks — the record everything else is built on.
--
-- THE UNIQUE CONSTRAINT BELOW IS THE MOST IMPORTANT LINE IN THIS FILE.
-- It is what makes ON CONFLICT DO NOTHING work (R5). Without it the clause
-- matches nothing, silently, and every sync run duplicates every attack — with
-- no error to notice.
--
-- CWL allows one attack per player per war, so attack_order is always 1 today.
-- It is kept anyway: T1.5 mandates it, and it keeps this table the same shape
-- as war_attacks, where multiple attacks are real.
--
-- Missed attacks are NOT stored. The API simply returns no attack for a player
-- who did not attack; the missed list is derived from roster minus attacks
-- (T4.3). Never insert a zero-star placeholder row to represent a miss.
-- ---------------------------------------------------------------------------
create table cwl_attacks (
  id                 uuid primary key default gen_random_uuid(),
  war_id             uuid not null references cwl_wars (id) on delete restrict,
  player_id          uuid not null references players (id) on delete restrict,
  attack_order       smallint not null default 1,
  stars              smallint not null check (stars between 0 and 3),
  destruction        numeric(5, 2) not null check (destruction between 0 and 100),
  defender_tag       text,
  defender_position  smallint,
  attacked_at        timestamptz,
  created_at         timestamptz not null default now(),
  deleted_at         timestamptz,

  unique (war_id, player_id, attack_order)
);

create index cwl_attacks_war_id_idx on cwl_attacks (war_id) where deleted_at is null;
create index cwl_attacks_player_id_idx on cwl_attacks (player_id) where deleted_at is null;


-- ---------------------------------------------------------------------------
-- cwl_bonuses — who received a bonus medal, and why.
--
-- R11: HUMAN DECISION DATA. No sync job may ever write here. The API does not
-- report bonus medal allocation at all — this exists nowhere but in our system,
-- which is exactly why it needs awarded_by and a note (T4.7).
-- ---------------------------------------------------------------------------
create table cwl_bonuses (
  id          uuid primary key default gen_random_uuid(),
  season_id   uuid not null references cwl_seasons (id) on delete restrict,
  player_id   uuid not null references players (id) on delete restrict,
  awarded_by  uuid not null references users (id) on delete restrict,
  awarded_at  timestamptz not null default now(),
  note        text,
  created_at  timestamptz not null default now(),
  updated_at  timestamptz,
  deleted_at  timestamptz,

  unique (season_id, player_id)
);

create trigger cwl_bonuses_set_updated_at
  before update on cwl_bonuses
  for each row execute function set_updated_at();


-- QA: foreign keys are not indexed automatically by PostgreSQL. Every one of
-- these columns is joined on by the CWL pages and the player profile (T3B.4).
create index cwl_bonuses_season_id_idx on cwl_bonuses (season_id) where deleted_at is null;
create index cwl_bonuses_player_id_idx on cwl_bonuses (player_id) where deleted_at is null;

-- ========================================================================
-- 003_war.sql
-- ========================================================================

-- T1.6 — Regular clan war tables.
--
-- R12 — war_targets is THE PLAN. war_attacks is WHAT HAPPENED.
-- They are separate tables and must stay that way. Never write a result into
-- war_targets: showing the gap between the two is the point (T6.5).

-- ---------------------------------------------------------------------------
-- wars — one row per war.
--
-- The API has no war id, so (clan_id, start_time) is the natural key: a clan
-- cannot be in two wars starting at the same instant.
-- ---------------------------------------------------------------------------
create table wars (
  id                 uuid primary key default gen_random_uuid(),
  clan_id            uuid not null references clans (id) on delete restrict,
  opponent_tag       text,
  opponent_name      text,
  team_size          smallint,
  state              text check (state in ('preparation', 'inWar', 'warEnded')),
  our_stars          smallint,
  their_stars        smallint,
  our_destruction    numeric(5, 2),
  their_destruction  numeric(5, 2),
  result             text check (result in ('win', 'lose', 'tie')),
  start_time         timestamptz not null,
  end_time           timestamptz,
  created_at         timestamptz not null default now(),
  updated_at         timestamptz,
  deleted_at         timestamptz,

  unique (clan_id, start_time)
);

create trigger wars_set_updated_at
  before update on wars
  for each row execute function set_updated_at();

create index wars_clan_id_idx on wars (clan_id) where deleted_at is null;


-- ---------------------------------------------------------------------------
-- war_targets — THE PLAN. Who was told to attack what.
--
-- R11: HUMAN DECISION DATA. scripts/sync/war.ts must never write here.
-- Leadership assigns targets; a member may claim an unassigned one (T6.4).
-- ---------------------------------------------------------------------------
create table war_targets (
  id               uuid primary key default gen_random_uuid(),
  war_id           uuid not null references wars (id) on delete restrict,
  player_id        uuid not null references players (id) on delete restrict,
  target_position  smallint not null,
  note             text,
  assigned_by      uuid references users (id) on delete restrict,
  assigned_at      timestamptz not null default now(),
  created_at       timestamptz not null default now(),
  updated_at       timestamptz,
  deleted_at       timestamptz,

  -- One assignment per player per war. Reassigning updates this row; the change
  -- is recorded in audit_log rather than by inserting a second target.
  unique (war_id, player_id)
);

create trigger war_targets_set_updated_at
  before update on war_targets
  for each row execute function set_updated_at();

create index war_targets_war_id_idx on war_targets (war_id) where deleted_at is null;


-- ---------------------------------------------------------------------------
-- war_attacks — WHAT HAPPENED. Written only by scripts/sync/war.ts (R11).
--
-- Same idempotency constraint as cwl_attacks. Here attack_order genuinely
-- varies: a regular war gives each player two attacks.
-- ---------------------------------------------------------------------------
create table war_attacks (
  id                 uuid primary key default gen_random_uuid(),
  war_id             uuid not null references wars (id) on delete restrict,
  player_id          uuid not null references players (id) on delete restrict,
  attack_order       smallint not null,
  stars              smallint not null check (stars between 0 and 3),
  destruction        numeric(5, 2) not null check (destruction between 0 and 100),
  defender_tag       text,
  defender_position  smallint,
  attacked_at        timestamptz,
  created_at         timestamptz not null default now(),
  deleted_at         timestamptz,

  unique (war_id, player_id, attack_order)
);

create index war_attacks_war_id_idx on war_attacks (war_id) where deleted_at is null;
create index war_attacks_player_id_idx on war_attacks (player_id) where deleted_at is null;


-- QA: unindexed foreign key. The player profile (T3B.4) reads targets by player.
create index war_targets_player_id_idx on war_targets (player_id) where deleted_at is null;

-- ========================================================================
-- 004_features.sql
-- ========================================================================

-- T1.7 — Remaining feature tables: raids, clan games, layouts, announcements,
-- push subscriptions.

-- ---------------------------------------------------------------------------
-- raid_seasons / raid_participants — Clan Capital raid weekends.
--
-- Game facts (R11), written by scripts/sync/raids.ts. The API keeps recent
-- raid history, so unlike CWL a missed run here can still be backfilled.
-- ---------------------------------------------------------------------------
create table raid_seasons (
  id          uuid primary key default gen_random_uuid(),
  clan_id     uuid not null references clans (id) on delete restrict,
  start_time  timestamptz not null,
  end_time    timestamptz,
  total_loot  integer,
  created_at  timestamptz not null default now(),
  updated_at  timestamptz,
  deleted_at  timestamptz,

  unique (clan_id, start_time)
);

create trigger raid_seasons_set_updated_at
  before update on raid_seasons
  for each row execute function set_updated_at();

create table raid_participants (
  id               uuid primary key default gen_random_uuid(),
  raid_season_id   uuid not null references raid_seasons (id) on delete restrict,
  player_id        uuid not null references players (id) on delete restrict,
  attacks_used     smallint,
  loot             integer,
  created_at       timestamptz not null default now(),
  updated_at       timestamptz,
  deleted_at       timestamptz,

  unique (raid_season_id, player_id)
);

create trigger raid_participants_set_updated_at
  before update on raid_participants
  for each row execute function set_updated_at();


-- ---------------------------------------------------------------------------
-- clan_games / clan_games_scores — Clan Games participation.
--
-- The API exposes NO per-season score. points is derived at T7.4 by snapshotting
-- each player's "Games Champion" achievement value at the start and end of the
-- period and taking the difference. Miss the start snapshot and that season's
-- score cannot be reconstructed.
-- ---------------------------------------------------------------------------
create table clan_games (
  id          uuid primary key default gen_random_uuid(),
  clan_id     uuid not null references clans (id) on delete restrict,
  season      text not null,                  -- 'YYYY-MM'
  start_time  timestamptz,
  end_time    timestamptz,
  created_at  timestamptz not null default now(),
  updated_at  timestamptz,
  deleted_at  timestamptz,

  unique (clan_id, season)
);

create trigger clan_games_set_updated_at
  before update on clan_games
  for each row execute function set_updated_at();

create table clan_games_scores (
  id             uuid primary key default gen_random_uuid(),
  clan_games_id  uuid not null references clan_games (id) on delete restrict,
  player_id      uuid not null references players (id) on delete restrict,
  points         integer,
  start_value    integer,                     -- achievement total at period start
  end_value      integer,                     -- and at period end; points is the difference
  created_at     timestamptz not null default now(),
  updated_at     timestamptz,
  deleted_at     timestamptz,

  unique (clan_games_id, player_id)
);

create trigger clan_games_scores_set_updated_at
  before update on clan_games_scores
  for each row execute function set_updated_at();


-- ---------------------------------------------------------------------------
-- base_layouts — the layout library (M7).
--
-- R11: human data. The API provides no layout information of any kind, so every
-- row here is member-supplied. image_url points at Supabase Storage; the file is
-- compressed in the browser before upload (T8.2) to stay inside the 1 GB tier.
-- ---------------------------------------------------------------------------
create table base_layouts (
  id           uuid primary key default gen_random_uuid(),
  clan_id      uuid not null references clans (id) on delete restrict,
  uploaded_by  uuid not null references users (id) on delete restrict,
  th_level     smallint not null,
  layout_type  text not null check (layout_type in ('war', 'farming', 'trophy')),
  copy_link    text not null,
  image_url    text,
  description  text,
  votes        integer not null default 0,
  created_at   timestamptz not null default now(),
  updated_at   timestamptz,
  deleted_at   timestamptz
);

create trigger base_layouts_set_updated_at
  before update on base_layouts
  for each row execute function set_updated_at();

create index base_layouts_clan_id_idx on base_layouts (clan_id) where deleted_at is null;
create index base_layouts_filter_idx on base_layouts (clan_id, th_level, layout_type)
  where deleted_at is null;


-- ---------------------------------------------------------------------------
-- announcements — the notice board (M8).
--
-- body is stored as plain text or restricted markdown and rendered safely.
-- Raw HTML is never rendered (T5.2) — anyone with posting rights would
-- otherwise be able to inject script into every member's browser.
-- ---------------------------------------------------------------------------
create table announcements (
  id          uuid primary key default gen_random_uuid(),
  clan_id     uuid not null references clans (id) on delete restrict,
  author_id   uuid not null references users (id) on delete restrict,
  title       text not null,
  body        text not null,
  pinned      boolean not null default false,
  created_at  timestamptz not null default now(),
  updated_at  timestamptz,
  deleted_at  timestamptz
);

create trigger announcements_set_updated_at
  before update on announcements
  for each row execute function set_updated_at();

create index announcements_clan_id_idx on announcements (clan_id, pinned, created_at desc)
  where deleted_at is null;


-- ---------------------------------------------------------------------------
-- push_subscriptions — Web Push endpoints (T5.5).
--
-- endpoint is unique: the browser issues one per installed app per device.
-- When the push service later returns 410 Gone the row is SOFT deleted (R4),
-- never removed.
-- ---------------------------------------------------------------------------
create table push_subscriptions (
  id          uuid primary key default gen_random_uuid(),
  user_id     uuid not null references users (id) on delete restrict,
  endpoint    text not null unique,
  p256dh      text not null,
  auth        text not null,
  created_at  timestamptz not null default now(),
  updated_at  timestamptz,
  deleted_at  timestamptz
);

create trigger push_subscriptions_set_updated_at
  before update on push_subscriptions
  for each row execute function set_updated_at();

create index push_subscriptions_user_id_idx on push_subscriptions (user_id)
  where deleted_at is null;


-- QA: unindexed foreign keys. All of these are read per player or per author by
-- the profile page (T3B.4) and the layout library (T8.4).
create index raid_participants_player_id_idx on raid_participants (player_id) where deleted_at is null;
create index clan_games_scores_player_id_idx on clan_games_scores (player_id) where deleted_at is null;
create index announcements_author_id_idx on announcements (author_id) where deleted_at is null;
create index base_layouts_uploaded_by_idx on base_layouts (uploaded_by) where deleted_at is null;

-- ========================================================================
-- 005_operational.sql
-- ========================================================================

-- T1.8 — Operational tables: sync_log, audit_log.
--
-- Neither table holds game data, but between them they are what stops the two
-- unrecoverable failures: a sync job dying unnoticed during CWL, and nobody
-- being able to say who changed what.

-- ---------------------------------------------------------------------------
-- sync_log — R9. Every job writes here at start and finish.
--
-- Drives the freshness indicator on every page (T4.8) and the failure push
-- alert (T5.8). A job that fails silently during CWL costs a season of data
-- that cannot be re-fetched from anywhere.
--
-- NOTE THE 'skipped' STATUS. R10: notInWar, warEnded, preparation and a missing
-- CWL group are ordinary conditions for most of the month, not failures. They
-- must be recorded as skipped, never as failed — a job that reports failure
-- three weeks out of four trains you to ignore the alerts that matter.
-- ---------------------------------------------------------------------------
create table sync_log (
  id               uuid primary key default gen_random_uuid(),
  job_type         text not null check (job_type in ('clans', 'cwl', 'war', 'raids', 'clan-games', 'backup')),
  clan_id          uuid references clans (id) on delete restrict,  -- null for family-wide jobs
  started_at       timestamptz not null default now(),
  finished_at      timestamptz,
  status           text not null check (status in ('running', 'success', 'skipped', 'failed')),
  skip_reason      text,          -- 'notInWar', 'noCwlGroup', ... when status = 'skipped'
  error            text,          -- R8: never put a player API token in here
  records_written  integer,
  created_at       timestamptz not null default now(),
  deleted_at       timestamptz
);

-- The freshness query is "latest successful run of job X for clan Y", so index
-- for that shape directly.
create index sync_log_freshness_idx
  on sync_log (job_type, clan_id, finished_at desc)
  where status = 'success';

create index sync_log_started_at_idx on sync_log (started_at desc);


-- ---------------------------------------------------------------------------
-- audit_log — R4. Every write is recorded: who, what, when.
--
-- Read by the viewer at T9.6. Without that page this record exists but is
-- invisible, and the protection against a departing member is theoretical.
--
-- before/after are jsonb snapshots of the changed row. Keep them small — store
-- the changed fields, not the entire entity.
--
-- deleted_at is present for consistency with section 4, but NOTHING SHOULD EVER
-- SET IT. An audit log you can quietly remove entries from is not an audit log.
-- ---------------------------------------------------------------------------
create table audit_log (
  id          uuid primary key default gen_random_uuid(),
  user_id     uuid references users (id) on delete restrict,
  clan_id     uuid references clans (id) on delete restrict,
  action      text not null,          -- 'create' | 'update' | 'delete' | 'publish' | ...
  entity      text not null,          -- table name, e.g. 'cwl_bonuses'
  entity_id   uuid,
  before      jsonb,
  after       jsonb,
  created_at  timestamptz not null default now(),
  deleted_at  timestamptz
);

create index audit_log_clan_id_idx on audit_log (clan_id, created_at desc);
create index audit_log_user_id_idx on audit_log (user_id, created_at desc);
create index audit_log_entity_idx on audit_log (entity, entity_id);

-- ========================================================================
-- 006_rls.sql
-- ========================================================================

-- T1.9 — Row Level Security.
--
-- READ THIS FILE LINE BY LINE BEFORE APPLYING IT (section 8).
--
-- This is the single most important security control in the system. Three clans
-- share one database, and application code will sometimes forget the clan filter
-- (R3 calls that the most common AI-generated bug in this project). These
-- policies are what stops a forgotten filter becoming a data leak.
--
-- RLS is the safety net, NOT a substitute for filtering by clan in every query.
--
-- Done when: with the anon key and no session, every table returns zero rows.
--
-- A useful property falls out of this design for free: T3.8's approval gate is
-- already enforced. A newly signed-up user has no clan_roles row, so
-- auth_clan_ids() returns the empty set and every policy below matches nothing.
-- A stranger with a verified tag and a valid session sees an empty application,
-- not a populated one — before any application-level gate is written.


-- ---------------------------------------------------------------------------
-- Which clans does the current user belong to?
--
-- security definer is load-bearing. The function reads clan_roles, and
-- clan_roles itself has an RLS policy that calls this function. Running as the
-- definer bypasses RLS inside the function body, which is what stops that
-- becoming infinite recursion.
--
-- set search_path = '' with fully qualified names prevents a search_path
-- hijack, which a security definer function is otherwise exposed to.
-- ---------------------------------------------------------------------------
create or replace function auth_clan_ids()
returns setof uuid
language sql
stable
security definer
set search_path = ''
as $$
  select clan_id
  from public.clan_roles
  where user_id = auth.uid()
    and deleted_at is null
$$;

-- Same, restricted to clans where the user is the leader. Used by audit_log.
create or replace function auth_leader_clan_ids()
returns setof uuid
language sql
stable
security definer
set search_path = ''
as $$
  select clan_id
  from public.clan_roles
  where user_id = auth.uid()
    and role = 'leader'
    and deleted_at is null
$$;


-- ---------------------------------------------------------------------------
-- Enable RLS everywhere.
--
-- Enabling RLS with no policy denies everything. Each table below then gets
-- exactly one select policy. That default-deny is deliberate: a table added in
-- a later migration and forgotten here is invisible rather than public.
-- ---------------------------------------------------------------------------
alter table clans              enable row level security;
alter table users              enable row level security;
alter table players            enable row level security;
alter table clan_roles         enable row level security;
alter table cwl_seasons        enable row level security;
alter table cwl_wars           enable row level security;
alter table cwl_attacks        enable row level security;
alter table cwl_bonuses        enable row level security;
alter table wars               enable row level security;
alter table war_targets        enable row level security;
alter table war_attacks        enable row level security;
alter table raid_seasons       enable row level security;
alter table raid_participants  enable row level security;
alter table clan_games         enable row level security;
alter table clan_games_scores  enable row level security;
alter table base_layouts       enable row level security;
alter table announcements      enable row level security;
alter table push_subscriptions enable row level security;
alter table sync_log           enable row level security;
alter table audit_log          enable row level security;


-- ---------------------------------------------------------------------------
-- Direct clan ownership — the table carries clan_id itself.
--
-- Every policy is `to authenticated`, so the anon role matches nothing at all.
-- ---------------------------------------------------------------------------
create policy "read own clans" on clans
  for select to authenticated
  using (id in (select auth_clan_ids()));

create policy "read own clan players" on players
  for select to authenticated
  using (clan_id in (select auth_clan_ids()));

create policy "read own clan roles" on clan_roles
  for select to authenticated
  using (clan_id in (select auth_clan_ids()));

create policy "read own clan cwl seasons" on cwl_seasons
  for select to authenticated
  using (clan_id in (select auth_clan_ids()));

create policy "read own clan wars" on wars
  for select to authenticated
  using (clan_id in (select auth_clan_ids()));

create policy "read own clan raid seasons" on raid_seasons
  for select to authenticated
  using (clan_id in (select auth_clan_ids()));

create policy "read own clan games" on clan_games
  for select to authenticated
  using (clan_id in (select auth_clan_ids()));

create policy "read own clan layouts" on base_layouts
  for select to authenticated
  using (clan_id in (select auth_clan_ids()));

create policy "read own clan announcements" on announcements
  for select to authenticated
  using (clan_id in (select auth_clan_ids()));


-- ---------------------------------------------------------------------------
-- Own row only.
-- ---------------------------------------------------------------------------
-- Own row only, deliberately. Widening this to "anyone in my clan" would expose
-- every member's email address, which is a privacy decision for the clan leader
-- (T0.11), not a convenience for a query.
--
-- KNOWN CONSEQUENCE: pages that display who did something — the author of an
-- announcement (T5.1), who awarded a bonus (T4.7), who published a roster
-- (T4B.9) — cannot resolve that name through this table yet. Prefer joining to
-- players.name, which is the in-game name members recognise anyway and is
-- already readable clan-wide. If a users join really is needed, add a policy
-- exposing id and display_name only, never email.
create policy "read own profile" on users
  for select to authenticated
  using (id = auth.uid());

create policy "read own push subscriptions" on push_subscriptions
  for select to authenticated
  using (user_id = auth.uid());


-- ---------------------------------------------------------------------------
-- Indirect ownership — clan_id is reached through a parent.
--
-- The exists-join pattern from Architecture.md 7.3. Deliberately NOT solved by
-- denormalising clan_id onto every child table: a denormalised copy can drift
-- out of step with its parent, and a policy reading the stale copy would grant
-- access the parent no longer allows.
-- ---------------------------------------------------------------------------
create policy "read own clan cwl wars" on cwl_wars
  for select to authenticated
  using (
    exists (
      select 1 from cwl_seasons s
      where s.id = cwl_wars.season_id
        and s.clan_id in (select auth_clan_ids())
    )
  );

create policy "read own clan cwl attacks" on cwl_attacks
  for select to authenticated
  using (
    exists (
      select 1 from cwl_wars w
      join cwl_seasons s on s.id = w.season_id
      where w.id = cwl_attacks.war_id
        and s.clan_id in (select auth_clan_ids())
    )
  );

create policy "read own clan cwl bonuses" on cwl_bonuses
  for select to authenticated
  using (
    exists (
      select 1 from cwl_seasons s
      where s.id = cwl_bonuses.season_id
        and s.clan_id in (select auth_clan_ids())
    )
  );

create policy "read own clan war targets" on war_targets
  for select to authenticated
  using (
    exists (
      select 1 from wars w
      where w.id = war_targets.war_id
        and w.clan_id in (select auth_clan_ids())
    )
  );

create policy "read own clan war attacks" on war_attacks
  for select to authenticated
  using (
    exists (
      select 1 from wars w
      where w.id = war_attacks.war_id
        and w.clan_id in (select auth_clan_ids())
    )
  );

create policy "read own clan raid participants" on raid_participants
  for select to authenticated
  using (
    exists (
      select 1 from raid_seasons r
      where r.id = raid_participants.raid_season_id
        and r.clan_id in (select auth_clan_ids())
    )
  );

create policy "read own clan games scores" on clan_games_scores
  for select to authenticated
  using (
    exists (
      select 1 from clan_games g
      where g.id = clan_games_scores.clan_games_id
        and g.clan_id in (select auth_clan_ids())
    )
  );


-- ---------------------------------------------------------------------------
-- Operational tables.
-- ---------------------------------------------------------------------------

-- Members need this for the freshness indicator on every page (T4.8).
-- clan_id is null for family-wide jobs, which every authenticated user may see.
create policy "read own clan sync log" on sync_log
  for select to authenticated
  using (clan_id is null or clan_id in (select auth_clan_ids()));

-- T9.6 — the audit log viewer is leader-only. Enforced here as well as in the
-- application, because "who changed what" includes entries about the people
-- reading it.
create policy "leaders read own clan audit log" on audit_log
  for select to authenticated
  using (clan_id in (select auth_leader_clan_ids()));


-- ---------------------------------------------------------------------------
-- Explicit grants.
--
-- Supabase normally handles this through ALTER DEFAULT PRIVILEGES at project
-- creation, so these would usually be redundant. They are stated anyway because
-- the failure mode when they are absent is confusing: RLS policies never even
-- get evaluated, and every query fails with "permission denied for table"
-- rather than returning the empty result you would expect from a policy.
--
-- A grant is not access. RLS still decides which rows come back; this only
-- decides who may ask.
-- ---------------------------------------------------------------------------
grant usage on schema public to anon, authenticated;

grant select on all tables in schema public to anon, authenticated;

grant execute on function auth_clan_ids() to anon, authenticated;
grant execute on function auth_leader_clan_ids() to anon, authenticated;


-- ---------------------------------------------------------------------------
-- No insert, update or delete policies exist, on purpose.
--
-- Every write today comes from scripts/sync/, which uses the service role key
-- and bypasses RLS by design — those jobs act for no user.
--
-- Human writes arrive later (T4.7 bonuses, T5.1 announcements, T8.3 layouts,
-- and all of Phase 4B). Each of those tasks adds its own write policy in its own
-- migration, scoped to the role that is allowed to perform it. Granting a broad
-- write policy here to "save a migration later" would hand every member the
-- ability to edit every human-decision table in their clan.
-- ---------------------------------------------------------------------------

-- ========================================================================
-- 007_member_snapshots.sql
-- ========================================================================

-- T2.9 — member_snapshots.
--
-- Supercell reports donations, trophies and war stars as CUMULATIVE totals that
-- reset monthly. A single reading is therefore meaningless on its own. Taking a
-- snapshot on every sync run and differencing across the season is the only way
-- to derive per-season figures (T3B.3) or to detect inactivity (T3B.5).
--
-- Without this table, the whole of Phase 3B has nothing to display.

create table member_snapshots (
  id                  uuid primary key default gen_random_uuid(),
  clan_id             uuid not null references clans (id) on delete restrict,
  player_id           uuid not null references players (id) on delete restrict,
  captured_at         timestamptz not null default now(),

  donations           integer,
  donations_received  integer,
  trophies            integer,
  war_stars           integer,
  th_level            smallint,
  role                text check (role in ('leader', 'co-leader', 'elder', 'member')),

  created_at          timestamptz not null default now(),
  deleted_at          timestamptz,

  -- ---------------------------------------------------------------------
  -- Resolving a conflict the spec leaves open.
  --
  -- T2.9 says "one row per player per run". R5 says running a job five times
  -- must change nothing after the first. Taken literally those disagree: with
  -- captured_at defaulting to now(), a re-run always inserts a second row.
  --
  -- Bucketing to the hour settles it. The hourly clans sync is idempotent
  -- within its hour, so a manual re-run, a retry, or one of GitHub's duplicate
  -- firings costs nothing.
  --
  -- It also bounds growth: at most 24 rows per player per day, roughly 1.3 M
  -- rows a year for 150 players, which is what keeps this inside the 500 MB
  -- free tier. Without the bucket, a 15-minute cadence would quadruple that.
  --
  -- The `at time zone 'UTC'` is required, not decorative. date_trunc() over a
  -- timestamptz depends on the session TimeZone, so it is not immutable and
  -- PostgreSQL rejects it outright in a generated column. Anchoring to UTC makes
  -- it immutable and gives a bucket that is stable no matter which timezone the
  -- connection happens to be in — which is also what section 4 asks for: stored
  -- UTC, converted only for display.
  -- ---------------------------------------------------------------------
  captured_hour       timestamp generated always as
                        (date_trunc('hour', captured_at at time zone 'UTC')) stored,

  unique (player_id, captured_hour)
);

-- Every profile and trend query is "this player, most recent first" (T3B.4).
create index member_snapshots_player_idx
  on member_snapshots (player_id, captured_at desc)
  where deleted_at is null;

-- The directory reads a whole clan at one point in time (T3B.2).
create index member_snapshots_clan_idx
  on member_snapshots (clan_id, captured_at desc)
  where deleted_at is null;


-- ---------------------------------------------------------------------------
-- RLS. A table added without this is invisible in the catalogue check but wide
-- open in production, so it goes in the same migration as the table itself.
-- ---------------------------------------------------------------------------
alter table member_snapshots enable row level security;

create policy "read own clan member snapshots" on member_snapshots
  for select to authenticated
  using (clan_id in (select auth_clan_ids()));

grant select on member_snapshots to anon, authenticated;

-- ========================================================================
-- 008_player_left_at.sql
-- ========================================================================

-- T3.9 — players.left_at.
--
-- Players move between the three clans, and some leave entirely. Neither event
-- may lose history: a member's CWL record belongs to the clan family regardless
-- of where they are now, and R4 means the row is never deleted.
--
-- Two distinct states, and conflating them is the bug to avoid:
--
--   moved between our clans  -> players.clan_id changes, left_at stays null.
--                               All history stays attached to the PLAYER, not
--                               the clan, so nothing needs rewriting.
--
--   left all three clans     -> left_at is set, clan_id is left as it was.
--                               The row and every attack, snapshot and bonus
--                               survive. Access is revoked by left_at, not by
--                               removing anything.
--
-- A returning member is simply left_at = null again, with their whole history
-- intact and their original row reused — which is why players.tag is unique.

alter table players
  add column left_at timestamptz;

comment on column players.left_at is
  'Set when the player is in none of the three clans. Never delete the row (R4) '
  '- their history is part of the clan family record. Null again if they return.';

-- The member directory and every sync read filters on "still here", so index for
-- that shape rather than the whole table.
create index players_active_idx
  on players (clan_id)
  where deleted_at is null and left_at is null;

-- T3B.5 needs the opposite view: who has gone, and when.
create index players_left_idx
  on players (left_at desc)
  where left_at is not null;

-- ========================================================================
-- 013_user_status.sql
-- ========================================================================

-- T3.8 — Account approval gate.
--
-- Magic-link signup means anyone with an email address can create an account.
-- Verification (T3.3) proves someone owns *a* Clash of Clans account, not that
-- they belong to *these three clans*. Those are different claims, and only the
-- second one should grant access.
--
-- Numbering: 009 is deliberately absent (it held cwl_signups from the superseded
-- T4.9), and 010-012 are taken by Phase 4B and T6.8. Hence 013.

alter table users
  add column status text not null default 'pending'
    check (status in ('pending', 'approved', 'rejected')),

  -- Which clan this person is asking to join.
  --
  -- Without this, T3.8's "a leader approves them manually" has no secure list to
  -- work from: a pending user has no clan_roles row, so there is no clan scope to
  -- filter on, and the only alternative is letting every leader read every
  -- pending account in the system. Set at verification time from the clan the
  -- verified player tag actually belongs to.
  add column requested_clan_id uuid references clans (id) on delete restrict,

  add column approved_by uuid references users (id) on delete restrict,
  add column approved_at timestamptz;

comment on column users.status is
  'pending until their verified player tag matches a current member of one of the '
  'three clans, or a leader approves them. Access is governed by clan_roles; this '
  'column is what the approval UI reads.';

create index users_pending_idx
  on users (requested_clan_id, created_at)
  where status = 'pending' and deleted_at is null;


-- ---------------------------------------------------------------------------
-- Leaders can see who is waiting for them — and only for their own clans.
--
-- The existing "read own profile" policy stays. This is additive: RLS combines
-- multiple SELECT policies with OR, so a user still reads their own row, and a
-- leader additionally reads pending applicants to clans they lead.
--
-- Scoped to auth_leader_clan_ids(), not auth_clan_ids(): an elder should not be
-- reading strangers' email addresses.
-- ---------------------------------------------------------------------------
create policy "leaders read pending applicants to their clans" on users
  for select to authenticated
  using (
    status = 'pending'
    and requested_clan_id in (select auth_leader_clan_ids())
  );


-- ---------------------------------------------------------------------------
-- Note on what is NOT here.
--
-- No UPDATE policy. Approval is a privileged write, and it happens through a
-- route handler that has already called requireRole(clanId, 'leader') and
-- written to audit_log (R4). Granting members a broad update on users would let
-- anyone approve themselves, which is the entire thing this migration prevents.
-- ---------------------------------------------------------------------------

-- ========================================================================
-- 014_service_role_grants.sql
-- ========================================================================

-- Fix forward for a defect in 006_rls.sql.
--
-- 006 granted select to `anon` and `authenticated` but never granted anything to
-- `service_role`. Every sync job uses the service key, so `npm run sync:clans`
-- failed on its first contact with real Supabase:
--
--   42501  permission denied for table clans
--
-- 006 has been applied, so per section 4 it is not edited — this migration
-- corrects it.
--
-- Why PGlite never caught it: the test harness connects as superuser and only
-- switches role to `anon` or `authenticated` to exercise RLS. It never acted as
-- `service_role`, so the missing grant was invisible. That is the limitation of a
-- stand-in, stated plainly in test/pg-harness.ts, showing up in practice.

grant usage on schema public to service_role;


-- ---------------------------------------------------------------------------
-- SELECT, INSERT, UPDATE — and deliberately NOT DELETE.
--
-- R4 says nothing is ever deleted: no DELETE statements, soft delete only,
-- because destroyed CWL history cannot be re-fetched from anywhere. Withholding
-- the privilege turns that rule from a convention the code must remember into
-- something the database enforces.
--
-- If a sync job ever tries a hard delete it now fails loudly with a permission
-- error, which is exactly the outcome R4 wants. Should a genuine need for a hard
-- delete appear, it should require a deliberate new migration and a reason —
-- never be available by default to a job that runs unattended every hour.
-- ---------------------------------------------------------------------------
grant select, insert, update on all tables in schema public to service_role;

-- Tables added by later migrations must inherit the same privileges, or the next
-- feature reintroduces this exact bug.
alter default privileges in schema public
  grant select, insert, update on tables to service_role;

alter default privileges in schema public
  grant select on tables to anon, authenticated;


-- ---------------------------------------------------------------------------
-- Sanity check after applying. Run this and confirm delete is absent:
--
--   select grantee, string_agg(privilege_type, ', ' order by privilege_type)
--   from information_schema.role_table_grants
--   where table_schema = 'public' and table_name = 'clans'
--   group by grantee;
--
-- Expect service_role to show INSERT, SELECT, UPDATE — and no DELETE.
-- ---------------------------------------------------------------------------

-- ========================================================================
-- 015_platform_admin.sql
-- ========================================================================

-- Leader-managed clans, replacing T1.10's hardcoded seed.
--
-- The spec treats clan tags as configuration: seed.sql inserts three rows, and a
-- fourth clan needs a migration. This makes them data the leader owns — added
-- through the admin UI, validated by lib/tags.ts, with sync filling in name,
-- badge and level afterwards.
--
-- That split respects R11: the leader supplies the TAG (a human decision, and one
-- no sync job may invent), while everything else about a clan is a game fact.
--
-- The bootstrap problem it creates:
--
--   seeing anything -> needs a clan_roles row
--   clan_roles      -> needs a clan to exist
--   a clan          -> needs a leader to add it
--   a leader        -> needs to see something
--
-- Clan-scoped roles cannot express "may create the first clan", so exactly one
-- platform-level capability is introduced. Deliberately one flag and nothing more:
-- every other permission in this system stays per clan.

alter table users
  add column is_platform_admin boolean not null default false;

comment on column users.is_platform_admin is
  'May add clans and approve accounts that belong to no clan yet. Exists only to '
  'break the bootstrap cycle - every other permission is per clan (T3.5).';

-- At most one platform admin. Not a technical requirement; it makes the blast
-- radius of this flag explicit, and a second one should be a deliberate act.
create unique index users_single_platform_admin
  on users ((true))
  where is_platform_admin and deleted_at is null;


-- ---------------------------------------------------------------------------
-- security definer, and for the usual reason: the policies below sit ON users,
-- so a policy reading users directly would recurse. Running as definer bypasses
-- RLS inside the body and breaks the cycle.
-- ---------------------------------------------------------------------------
create or replace function auth_is_platform_admin()
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select coalesce(
    (select is_platform_admin
     from public.users
     where id = auth.uid() and deleted_at is null),
    false)
$$;

grant execute on function auth_is_platform_admin() to anon, authenticated;


-- ---------------------------------------------------------------------------
-- Ownership claim.
--
-- The bootstrap cannot be done from application code alone: promoting yourself
-- requires a write that no policy grants, and granting that policy would let
-- anyone promote themselves.
--
-- So it is a definer function with one condition that can only ever be true
-- once: it promotes the caller ONLY IF the platform currently has no admin. The
-- first person through the door can claim it; nobody after them can, and there
-- is no argument to tamper with.
--
-- The application adds a second, independent check — the caller's email must
-- match OWNER_EMAIL — so a stranger reaching the URL first still cannot claim it.
-- ---------------------------------------------------------------------------
create or replace function claim_platform_ownership()
returns boolean
language plpgsql
security definer
set search_path = ''
as $$
declare
  existing integer;
begin
  if auth.uid() is null then
    return false;
  end if;

  select count(*) into existing
  from public.users
  where is_platform_admin and deleted_at is null;

  if existing > 0 then
    return false;
  end if;

  -- Signal the guard trigger that this write is the sanctioned bootstrap.
  --
  -- The trigger is `security invoker`, so inside this definer function it still
  -- runs as the calling user and would otherwise block the very write it exists
  -- to protect. A transaction-local GUC is the signal: `true` scopes it to this
  -- transaction, so it cannot leak into any later statement, and no client can
  -- set it usefully because reaching the update at all requires this function.
  perform set_config('clanbridge.bootstrap', 'on', true);

  update public.users
  set is_platform_admin = true,
      status = 'approved',
      approved_at = now()
  where id = auth.uid();

  insert into public.audit_log (user_id, action, entity, entity_id, after)
  values (auth.uid(), 'claim-ownership', 'users', auth.uid(),
          jsonb_build_object('is_platform_admin', true));

  return true;
end;
$$;

-- Postgres grants EXECUTE on new functions to PUBLIC by default, so granting to
-- `authenticated` alone would still leave anon able to call this. It would return
-- false for them (auth.uid() is null), but an unauthenticated caller should not
-- be able to reach the ownership claim at all.
revoke execute on function claim_platform_ownership() from public;
grant execute on function claim_platform_ownership() to authenticated;


-- ---------------------------------------------------------------------------
-- Privileges for the writes below.
--
-- A GRANT and a POLICY are different gates and both are required: the grant says
-- whether the role may attempt the statement at all, the policy says which rows
-- it may touch. 006 granted only SELECT to authenticated, so without this every
-- policy below would be unreachable behind "permission denied for table".
--
-- That is the same defect 014 fixed for service_role, in a different place. It
-- surfaced here only because these are the first write policies in the project.
--
-- Granted narrowly — three tables, no DELETE anywhere (R4). Each future feature
-- grants what it needs rather than inheriting a blanket permission.
-- ---------------------------------------------------------------------------
grant insert, update on clans      to authenticated;
grant insert, update on clan_roles to authenticated;
grant insert, update on users      to authenticated;


-- ---------------------------------------------------------------------------
-- Write policies.
--
-- 006 shipped select-only on purpose, so each feature adds its own writes scoped
-- to the role permitted to perform them. These are the first.
-- ---------------------------------------------------------------------------

-- Adding a clan. INSERT uses `with check`, not `using`.
create policy "platform admin adds clans" on clans
  for insert to authenticated
  with check (auth_is_platform_admin());

-- Renaming or deactivating a clan. Sync also updates clans, but it uses the
-- service key and bypasses RLS entirely.
create policy "platform admin updates clans" on clans
  for update to authenticated
  using (auth_is_platform_admin())
  with check (auth_is_platform_admin());

-- The platform admin must see every clan, including one just created before any
-- clan_roles row exists for it.
create policy "platform admin reads all clans" on clans
  for select to authenticated
  using (auth_is_platform_admin());

-- Granting a role: the platform admin, or a leader of that clan.
create policy "admin or leader grants roles" on clan_roles
  for insert to authenticated
  with check (
    auth_is_platform_admin()
    or clan_id in (select auth_leader_clan_ids())
  );

create policy "admin or leader changes roles" on clan_roles
  for update to authenticated
  using (
    auth_is_platform_admin()
    or clan_id in (select auth_leader_clan_ids())
  )
  with check (
    auth_is_platform_admin()
    or clan_id in (select auth_leader_clan_ids())
  );

create policy "platform admin reads all roles" on clan_roles
  for select to authenticated
  using (auth_is_platform_admin());

-- T3.8 — approving an account. A leader may approve applicants to their own clan;
-- the platform admin may approve anyone, including someone with no clan yet.
--
-- Note what this does NOT allow: promoting anyone to platform admin. That column
-- is only ever written by claim_platform_ownership(), which can fire once.
-- Approving an account is a FUNCTION, not a policy.
--
-- It was first written as an RLS update policy, and that was the wrong tool.
-- Approval is a privileged operation that must also write audit_log (R4), so
-- expressing it as "which rows may this role write" splits one indivisible act
-- into a permission check and a separate, forgettable audit insert.
--
-- As a definer function it is atomic, always audited, and the authority check
-- lives in one readable place instead of a WITH CHECK expression. It also
-- matches claim_platform_ownership() above, so every privileged write in this
-- schema works the same way.
--
-- Consequence: users has NO general update policy. A member may edit their own
-- row (below), and nothing else about a user is writable from a session.
create or replace function approve_account(target uuid)
returns boolean
language plpgsql
security definer
set search_path = ''
as $$
declare
  target_clan   uuid;
  target_status text;
  allowed       boolean;
begin
  if auth.uid() is null or target is null then
    return false;
  end if;

  select requested_clan_id, status into target_clan, target_status
  from public.users
  where id = target and deleted_at is null;

  if not found or target_status <> 'pending' then
    return false;
  end if;

  -- Nobody approves themselves, regardless of rank.
  if target = auth.uid() then
    raise exception 'accounts cannot approve themselves';
  end if;

  allowed := public.auth_is_platform_admin()
    or (target_clan is not null
        and target_clan in (select public.auth_leader_clan_ids()));

  if not allowed then
    return false;
  end if;

  perform set_config('clanbridge.bootstrap', 'on', true);

  update public.users
  set status      = 'approved',
      approved_by = auth.uid(),
      approved_at = now()
  where id = target;

  insert into public.audit_log (user_id, clan_id, action, entity, entity_id, after)
  values (auth.uid(), target_clan, 'approve', 'users', target,
          jsonb_build_object('status', 'approved'));

  return true;
end;
$$;

revoke execute on function approve_account(uuid) from public;
grant execute on function approve_account(uuid) to authenticated;

-- The mirror image, so a rejection is recorded rather than left pending forever.
create or replace function reject_account(target uuid)
returns boolean
language plpgsql
security definer
set search_path = ''
as $$
declare
  target_clan uuid;
  allowed     boolean;
begin
  if auth.uid() is null or target is null or target = auth.uid() then
    return false;
  end if;

  select requested_clan_id into target_clan
  from public.users where id = target and deleted_at is null;

  if not found then
    return false;
  end if;

  allowed := public.auth_is_platform_admin()
    or (target_clan is not null
        and target_clan in (select public.auth_leader_clan_ids()));

  if not allowed then
    return false;
  end if;

  perform set_config('clanbridge.bootstrap', 'on', true);

  update public.users set status = 'rejected' where id = target;

  insert into public.audit_log (user_id, clan_id, action, entity, entity_id, after)
  values (auth.uid(), target_clan, 'reject', 'users', target,
          jsonb_build_object('status', 'rejected'));

  return true;
end;
$$;

revoke execute on function reject_account(uuid) from public;
grant execute on function reject_account(uuid) to authenticated;

create policy "platform admin reads all users" on users
  for select to authenticated
  using (auth_is_platform_admin());

-- Everyone may create and maintain their own profile row on first sign-in.
create policy "own profile insert" on users
  for insert to authenticated
  with check (id = auth.uid());

-- Own row only, for a display name. Status and is_platform_admin are blocked by
-- the trigger below, so this cannot become a route to privilege.
create policy "own profile update" on users
  for update to authenticated
  using (id = auth.uid())
  with check (id = auth.uid());


-- ---------------------------------------------------------------------------
-- Guard against the obvious escalation.
--
-- "own profile update" lets a member edit their own row, which would otherwise
-- let them set is_platform_admin or status themselves. A trigger blocks both
-- unless the write comes from a definer function or the service key.
-- ---------------------------------------------------------------------------
create or replace function guard_user_privilege_columns()
returns trigger
language plpgsql
security invoker
set search_path = ''
as $$
begin
  -- Constrain END-USER SESSIONS only.
  --
  -- Deliberately an allow-list of the two untrusted roles rather than a
  -- deny-list of trusted ones. Everything else — service_role for sync jobs,
  -- postgres for migrations and admin tooling — is already privileged by other
  -- means, and an earlier version that tested `role = 'service_role'` blocked
  -- the migration runner itself.
  if current_user not in ('authenticated', 'anon') then
    return new;
  end if;

  -- The definer functions above set this transaction-locally before their
  -- update. Nothing else sets it, and each function checks the caller's
  -- authority before doing so.
  if current_setting('clanbridge.bootstrap', true) = 'on' then
    return new;
  end if;

  if new.is_platform_admin is distinct from old.is_platform_admin then
    raise exception 'is_platform_admin cannot be set directly';
  end if;

  -- status is only ever changed by approve_account() / reject_account(), which
  -- set the bootstrap GUC above. A direct session write is always refused,
  -- including a member trying to approve themselves.
  if new.status is distinct from old.status then
    raise exception 'status is set by approve_account()/reject_account(), not directly';
  end if;

  return new;
end;
$$;

create trigger users_guard_privilege_columns
  before update on users
  for each row execute function guard_user_privilege_columns();

-- ========================================================================
-- 016_player_verification.sql
-- ========================================================================

-- T3.3 — Player verification: link a verified Clash of Clans account to a user.
--
-- WHY THIS IS A FUNCTION AND NOT A POLICY
--
-- `players` has exactly one policy — "read own clan players" (006) — and exactly
-- one grant: select. 015 handed `insert, update` to authenticated on clans,
-- clan_roles and users, and deliberately not on players. That is correct and
-- stays correct: players is a GAME FACT table (R11), owned by scripts/sync/, and
-- a session must never be able to write a player's name, clan or town hall.
--
-- But verification has to write two columns of it. So the write happens here, in
-- a security definer function that is the ONLY path, rather than by opening the
-- table up with an update policy and trusting a WITH CHECK expression to keep a
-- session away from the other columns.
--
-- This is the same reasoning 015 records at lines 199-207 for approve_account(),
-- and the same shape: authority check, then the write, then audit_log, all in one
-- indivisible act that cannot be half-performed.
--
-- R8 — the member's in-game API token never reaches this file. It is verified
-- against Supercell in /api/verify and discarded there. Nothing about it is a
-- parameter here; by the time this runs, ownership is already proven.


-- ---------------------------------------------------------------------------
-- link_verified_player(p_tag)
--
-- Called by /api/verify AFTER Supercell's verifytoken endpoint returned ok.
--
-- Returns jsonb rather than boolean because the caller needs to tell three
-- different outcomes apart in the UI, and a bare false cannot:
--
--   {"ok": true,  "player_id": …, "clan_id": …}
--   {"ok": false, "reason": "no_session"}
--   {"ok": false, "reason": "not_a_member"}
--
-- A tag that belongs to no clan on this platform is refused and NO player row is
-- invented for it. Two reasons:
--
--   1. R11 — players is written by sync jobs. A row created here would have no
--      clan, would never be updated by any job, and would sit in the table
--      looking like a member forever.
--   2. It is what makes T3.8's done-when true by construction: "an account
--      created with a random email and a stranger's verified tag can see no clan
--      data". Such a tag never links, so requested_clan_id stays null, so no
--      leader ever sees them in a queue, so they stay pending forever.
--
-- Manual leader approval is the confirmed policy for this deployment: verifying
-- a tag NEVER approves an account. It proves ownership and routes the applicant
-- to the right leader. Approval remains approve_account() (015), by a human.
-- ---------------------------------------------------------------------------
create or replace function link_verified_player(p_tag text)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_player_id uuid;
  v_clan_id   uuid;
  v_owner     uuid;
begin
  if auth.uid() is null then
    return jsonb_build_object('ok', false, 'reason', 'no_session');
  end if;

  if p_tag is null then
    return jsonb_build_object('ok', false, 'reason', 'not_a_member');
  end if;

  -- clan_id is not null, so a player kept for history after leaving all three
  -- clans (T3.9 sets left_at) cannot be used to gain access. left_at is checked
  -- too: a departed member must be re-approved rather than walking back in.
  select id, clan_id, user_id
    into v_player_id, v_clan_id, v_owner
  from public.players
  where tag = p_tag
    and deleted_at is null
    and left_at is null
    and clan_id is not null;

  if not found then
    return jsonb_build_object('ok', false, 'reason', 'not_a_member');
  end if;

  -- Tag theft. The token proved the CALLER owns this game account, so a row
  -- already pointing at somebody else means either an account changed hands or
  -- an attempt to take over a teammate's profile. Neither is resolvable here —
  -- it raises so /api/verify can surface it and a leader can look into it.
  if v_owner is not null and v_owner <> auth.uid() then
    raise exception 'player already linked to another account';
  end if;

  perform set_config('clanbridge.bootstrap', 'on', true);

  update public.players
  set verified = true,
      user_id  = auth.uid()
  where id = v_player_id;

  -- THIS is what puts the applicant in front of the right leader. 013's
  -- "leaders read pending applicants to their clans" policy filters on
  -- requested_clan_id, and the guard trigger below now refuses a direct write to
  -- it — so this function is the only way it can ever be set, and a member
  -- cannot nominate themselves into a clan they have no account in.
  update public.users
  set requested_clan_id = v_clan_id
  where id = auth.uid()
    and deleted_at is null;

  insert into public.audit_log (user_id, clan_id, action, entity, entity_id, after)
  values (auth.uid(), v_clan_id, 'verify', 'players', v_player_id,
          jsonb_build_object('verified', true, 'tag', p_tag));

  return jsonb_build_object(
    'ok', true,
    'player_id', v_player_id,
    'clan_id', v_clan_id);
end;
$$;

revoke execute on function link_verified_player(text) from public;
grant execute on function link_verified_player(text) to authenticated;

comment on function link_verified_player(text) is
  'T3.3 - links a verified player tag to auth.uid() and routes the account to '
  'that clan''s leader for approval. The only write path to players from a '
  'session; players is otherwise select-only for authenticated (R11).';


-- ---------------------------------------------------------------------------
-- Close the requested_clan_id escalation.
--
-- 015 added "own profile update" so a member could set their own display name,
-- and guarded the two columns that were obviously dangerous: is_platform_admin
-- and status. requested_clan_id was not guarded, and it should have been.
--
-- Without this, any signed-in user can run
--
--     update users set requested_clan_id = '<any clan uuid>' where id = auth.uid()
--
-- and appear in that clan leader's pending-applicant list, having verified
-- nothing. It is not a data leak — 013's policy only exposes the applicant's own
-- row to the leader, and approval is still a deliberate human act — but it lets
-- a stranger put themselves in front of a leader who may click approve out of
-- habit. The whole point of the pending queue is that everything in it arrived
-- by proving something.
--
-- Now the only writer is link_verified_player() above, which sets it to the clan
-- the verified tag actually plays in.
--
-- This is a `create or replace` of 015's function; the trigger it backs
-- (users_guard_privilege_columns) is unchanged and stays attached.
-- ---------------------------------------------------------------------------
create or replace function guard_user_privilege_columns()
returns trigger
language plpgsql
security invoker
set search_path = ''
as $$
begin
  -- Constrain END-USER SESSIONS only.
  --
  -- Deliberately an allow-list of the two untrusted roles rather than a
  -- deny-list of trusted ones. Everything else — service_role for sync jobs,
  -- postgres for migrations and admin tooling — is already privileged by other
  -- means, and an earlier version that tested `role = 'service_role'` blocked
  -- the migration runner itself.
  if current_user not in ('authenticated', 'anon') then
    return new;
  end if;

  -- The definer functions set this transaction-locally before their update.
  -- Nothing else sets it, and each one checks the caller's authority first.
  if current_setting('clanbridge.bootstrap', true) = 'on' then
    return new;
  end if;

  if new.is_platform_admin is distinct from old.is_platform_admin then
    raise exception 'is_platform_admin cannot be set directly';
  end if;

  -- status is only ever changed by approve_account() / reject_account(), which
  -- set the bootstrap GUC above. A direct session write is always refused,
  -- including a member trying to approve themselves.
  if new.status is distinct from old.status then
    raise exception 'status is set by approve_account()/reject_account(), not directly';
  end if;

  -- New in 016. See the block comment above.
  if new.requested_clan_id is distinct from old.requested_clan_id then
    raise exception 'requested_clan_id is set by link_verified_player(), not directly';
  end if;

  return new;
end;
$$;


-- ---------------------------------------------------------------------------
-- Verify:
--
--   select proname, prosecdef from pg_proc where proname = 'link_verified_player';
--     -- expect one row, prosecdef = true
--
--   select has_table_privilege('authenticated', 'players', 'update');
--     -- expect FALSE. If this is ever true, the function above has been made
--     -- redundant by a grant and players is writable from a session.
-- ---------------------------------------------------------------------------

-- ========================================================================
-- 017_approval_grants_membership.sql
-- ========================================================================

-- T3.8 — Approving an account must also grant membership of the clan.
--
-- THE DEFECT
--
-- 015's approve_account() sets users.status = 'approved' and stops. But status is
-- only half of the gate. The other half is clan_roles: auth_clan_ids() reads it,
-- every clan-scoped policy in 006 filters on it, and visibleClans() builds the
-- switcher from it.
--
-- So an approved account with no clan_roles row is approved and still sees
-- nothing — past the /pending redirect, into an application with no clans in it.
-- The leader has clicked Approve, the applicant has been told they are in, and
-- the screen is empty. Nothing reports an error, because nothing failed.
--
-- 006 (lines 272-283) describes the empty-clan_roles state as the thing that
-- protects a stranger from seeing data, which is right. It is not a state an
-- APPROVED member should ever be left in.
--
-- WHY THIS REPLACES THE FUNCTION RATHER THAN ADDING A SECOND STEP
--
-- The alternative is for the admin page to call approve_account() and then insert
-- clan_roles itself — two round trips, no transaction. A failure between them
-- leaves exactly the half-approved state described above, and the leader has no
-- way to tell it happened.
--
-- 015 argued this same point when it made approval a function instead of a
-- policy: one indivisible act, always audited, authority checked in one readable
-- place. Granting the role is part of that act.
--
-- Section 4 — 015 is applied and is not edited. This fixes forward by replacing
-- the function; every check in the original is preserved verbatim below.


create or replace function approve_account(target uuid)
returns boolean
language plpgsql
security definer
set search_path = ''
as $$
declare
  target_clan   uuid;
  target_status text;
  allowed       boolean;
begin
  if auth.uid() is null or target is null then
    return false;
  end if;

  select requested_clan_id, status into target_clan, target_status
  from public.users
  where id = target and deleted_at is null;

  if not found or target_status <> 'pending' then
    return false;
  end if;

  -- Nobody approves themselves, regardless of rank.
  if target = auth.uid() then
    raise exception 'accounts cannot approve themselves';
  end if;

  allowed := public.auth_is_platform_admin()
    or (target_clan is not null
        and target_clan in (select public.auth_leader_clan_ids()));

  if not allowed then
    return false;
  end if;

  -- New in 017. An account with no clan to be approved INTO cannot be approved:
  -- there is no membership to grant, and letting it through produces the empty
  -- application described above. The applicant must verify a player tag first,
  -- which is what sets requested_clan_id (016).
  if target_clan is null then
    return false;
  end if;

  perform set_config('clanbridge.bootstrap', 'on', true);

  update public.users
  set status      = 'approved',
      approved_by = auth.uid(),
      approved_at = now()
  where id = target;

  -- The membership itself.
  --
  -- 'member' always, never the player's in-game rank. R11 — clan_roles is an
  -- application permission, and the in-game role is a game fact that sync owns.
  -- Copying one into the other would mean a promotion in game silently granted
  -- someone the ability to publish rosters and award bonuses here.
  --
  -- on conflict do nothing because unique (user_id, clan_id) already exists and a
  -- re-approval must not fail — and must not silently DOWNGRADE a leader back to
  -- member either, which an upsert would.
  insert into public.clan_roles (user_id, clan_id, role)
  values (target, target_clan, 'member')
  on conflict (user_id, clan_id) do nothing;

  insert into public.audit_log (user_id, clan_id, action, entity, entity_id, after)
  values (auth.uid(), target_clan, 'approve', 'users', target,
          jsonb_build_object('status', 'approved', 'role', 'member'));

  return true;
end;
$$;

revoke execute on function approve_account(uuid) from public;
grant execute on function approve_account(uuid) to authenticated;

comment on function approve_account(uuid) is
  'T3.8 - lifts the pending gate AND grants member of the requested clan, in one '
  'transaction. Approving without the clan_roles row leaves the account past the '
  '/pending redirect with no clans visible (017).';


-- ---------------------------------------------------------------------------
-- Verify:
--
--   -- after approving, the applicant must have BOTH
--   select status from users where id = '<applicant>';          -- 'approved'
--   select role from clan_roles where user_id = '<applicant>';  -- 'member'
--
-- If the second is empty, this migration did not take effect and the member is
-- looking at an empty application right now.
-- ---------------------------------------------------------------------------

-- ========================================================================
-- 018_admin_may_approve_clanless.sql
-- ========================================================================

-- 017 was too strict, and broke a capability 015 deliberately created.
--
-- 015 documents is_platform_admin as: "May add clans and approve accounts that
-- belong to no clan yet. Exists only to break the bootstrap cycle."
--
-- 017 then refused every approval where requested_clan_id is null, to stop a
-- member being approved into an application with no clans in it. That reasoning
-- is right for a LEADER — a leader approving someone with no clan has nothing to
-- approve them into, and no way to give them a role afterwards.
--
-- It is wrong for the platform admin, who has both. Refusing them removes the
-- exact escape hatch that exists for when the normal path is unavailable: a
-- member whose tag has not synced yet, or an account that must be let in before
-- the clan it belongs to has been added.
--
-- So the rule becomes conditional on who is asking:
--
--   leader, no requested clan  -> refused. Nothing to approve into.
--   leader, requested clan     -> approved + granted member of that clan.
--   platform admin, no clan    -> approved, no role granted. Deliberate act by
--                                 the one person who can then grant one.
--   platform admin, with clan  -> approved + granted member of that clan.
--
-- The guarantee 017 was protecting survives where it matters: nobody reaches the
-- approved state with no clan role by accident. It now takes the platform admin
-- choosing to do it.
--
-- Section 4 — 017 is applied and is not edited. Fixed forward.

create or replace function approve_account(target uuid)
returns boolean
language plpgsql
security definer
set search_path = ''
as $$
declare
  target_clan   uuid;
  target_status text;
  is_admin      boolean;
  allowed       boolean;
begin
  if auth.uid() is null or target is null then
    return false;
  end if;

  select requested_clan_id, status into target_clan, target_status
  from public.users
  where id = target and deleted_at is null;

  if not found or target_status <> 'pending' then
    return false;
  end if;

  -- Nobody approves themselves, regardless of rank.
  if target = auth.uid() then
    raise exception 'accounts cannot approve themselves';
  end if;

  is_admin := public.auth_is_platform_admin();

  allowed := is_admin
    or (target_clan is not null
        and target_clan in (select public.auth_leader_clan_ids()));

  if not allowed then
    return false;
  end if;

  -- 017's guarantee, narrowed to the case it was actually about. A leader
  -- approving a clanless account would leave them past the /pending redirect
  -- with nothing to see and no role the leader could grant.
  if target_clan is null and not is_admin then
    return false;
  end if;

  perform set_config('clanbridge.bootstrap', 'on', true);

  update public.users
  set status      = 'approved',
      approved_by = auth.uid(),
      approved_at = now()
  where id = target;

  -- 'member' always, never the player's in-game rank. R11 — clan_roles is an
  -- application permission and the in-game role is a game fact that sync owns.
  -- Copying one into the other would mean a promotion in game silently granted
  -- someone the ability to publish rosters and award bonuses here.
  --
  -- on conflict do nothing because unique (user_id, clan_id) already exists: a
  -- re-approval must not fail, and must not DOWNGRADE an existing leader back to
  -- member either, which an upsert would.
  if target_clan is not null then
    insert into public.clan_roles (user_id, clan_id, role)
    values (target, target_clan, 'member')
    on conflict (user_id, clan_id) do nothing;
  end if;

  insert into public.audit_log (user_id, clan_id, action, entity, entity_id, after)
  values (auth.uid(), target_clan, 'approve', 'users', target,
          jsonb_build_object(
            'status', 'approved',
            'role', case when target_clan is null then null else 'member' end));

  return true;
end;
$$;

revoke execute on function approve_account(uuid) from public;
grant execute on function approve_account(uuid) to authenticated;

comment on function approve_account(uuid) is
  'T3.8 - lifts the pending gate, and grants member of the requested clan when '
  'there is one. A leader cannot approve a clanless account (nothing to approve '
  'into); the platform admin can, as 015 intends (017, 018).';

-- ========================================================================
-- 019_cwl_war_members.sql
-- ========================================================================

-- T4.1/T4.3 — cwl_war_members: the roster the API reported for one CWL war.
--
-- WHY THIS TABLE HAS TO EXIST
--
-- 002_cwl.sql:76-78 forbids storing a miss:
--
--     "Missed attacks are NOT stored. The API simply returns no attack for a
--      player who did not attack; the missed list is derived from roster minus
--      attacks (T4.3). Never insert a zero-star placeholder row."
--
-- That rule is right — a placeholder row is indistinguishable from a real zero
-- star attack once it is in the table. But "roster minus attacks" needs a
-- roster, and until now nothing stored one. cwl_wars has 18 columns and not one
-- of them holds who was in the war, so T4.5's central feature ("a clear list of
-- who has not attacked") had no source at all.
--
-- The alternative considered was a jsonb column on cwl_wars. Rejected: every
-- missed-attack query would have to unpack JSON, and T4B.11's plan-versus-
-- reality comparison (leader's roster vs who actually played) becomes a join
-- against a real table or an unpleasant mess against a document.
--
--
-- R11 — THIS IS A GAME FACT, NOT A HUMAN DECISION.
--
-- This is who the API said was in the war. It is NOT cwl_rosters, which is who
-- the leader picked (T4B.6, still a stub). R12 exists precisely to keep those
-- two apart: showing the difference between them is the most useful thing this
-- system does, and it is destroyed the moment a sync job writes to the leader's
-- table or a form writes to this one.
--
-- Written only by scripts/sync/cwl.ts.


-- ---------------------------------------------------------------------------
-- Append-only, deliberately shaped like cwl_attacks rather than like cwl_wars:
-- no updated_at and no set_updated_at trigger.
--
-- A war roster is fixed once the war starts. If the API ever reports a
-- different roster for a war we have already recorded, that is a fact worth
-- noticing, not silently overwriting (R5). The unique constraint below makes
-- the re-insert a no-op instead.
-- ---------------------------------------------------------------------------
create table cwl_war_members (
  id            uuid primary key default gen_random_uuid(),
  war_id        uuid not null references cwl_wars (id) on delete restrict,
  player_id     uuid not null references players (id) on delete restrict,
  map_position  smallint,
  th_level      smallint,
  created_at    timestamptz not null default now(),
  deleted_at    timestamptz,

  -- The idempotency key. Same role as cwl_attacks' three-column constraint:
  -- without it ON CONFLICT DO NOTHING matches nothing and every run duplicates
  -- the entire roster, silently.
  unique (war_id, player_id)
);

create index cwl_war_members_war_id_idx
  on cwl_war_members (war_id) where deleted_at is null;
create index cwl_war_members_player_id_idx
  on cwl_war_members (player_id) where deleted_at is null;

comment on table cwl_war_members is
  'Who the API reported in a CWL war (a game fact, R11). Missed attacks are '
  'this minus cwl_attacks. Not to be confused with cwl_rosters, which is who '
  'the leader selected (R12).';


-- ---------------------------------------------------------------------------
-- RLS — the same two-level join cwl_attacks uses.
--
-- There is no clan_id on this table, exactly as there is none on cwl_wars or
-- cwl_attacks. Scoping runs cwl_war_members -> cwl_wars -> cwl_seasons.clan_id.
-- test/migrations.test.ts:308 calls the two-level join "the policy most likely
-- to be written wrongly", so this one is a deliberate copy of the shape already
-- proven there rather than a fresh attempt.
-- ---------------------------------------------------------------------------
alter table cwl_war_members enable row level security;

create policy "read own clan cwl war members" on cwl_war_members
  for select to authenticated
  using (
    exists (
      select 1
      from cwl_wars w
      join cwl_seasons s on s.id = w.season_id
      where w.id = cwl_war_members.war_id
        and s.clan_id in (select auth_clan_ids())
    )
  );

-- 006 grants select to anon/authenticated on all tables that existed then, and
-- 014's alter default privileges covers tables created afterwards. Granted
-- explicitly anyway: relying on a default privilege that was set in a different
-- migration is how 014 came to exist in the first place (every sync job failed
-- with 42501 because 006 forgot service_role).
grant select on cwl_war_members to anon, authenticated;
grant select, insert, update on cwl_war_members to service_role;

-- No delete grant, for anybody. R4.


-- ---------------------------------------------------------------------------
-- Verify:
--
--   select has_table_privilege('service_role', 'cwl_war_members', 'delete');
--     -- expect FALSE (R4)
--
--   select count(*) from pg_policies where tablename = 'cwl_war_members';
--     -- expect 1
-- ---------------------------------------------------------------------------

commit;

-- Verify from your terminal afterwards:  npm run supabase:check
-- Expect: 21/21 tables returning zero rows to the anon key (T1.9).
