// Concatenate the applicable migrations into one transactional file.
//
//   npm run migrations:bundle   ->   supabase/apply-all.sql
//
// Why this exists: applying nine files by hand in the right order invites a
// mistake, and a half-applied schema is worse than none — 002 references tables
// from 001, 006 references every table, and a missed file leaves RLS off
// somewhere. Wrapping the lot in BEGIN/COMMIT makes it all-or-nothing.
//
// Generated, never edited. The individual files under supabase/migrations/ stay
// the source of truth (section 4: numbered files, never edited once applied).

import { readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { PHASE1_MIGRATIONS } from "../test/pg-harness";

const DIR = join(process.cwd(), "supabase");

function main(): void {
  const parts: string[] = [
    "-- ClanBridge — all applicable migrations, in order, as one transaction.",
    "--",
    "-- GENERATED by `npm run migrations:bundle`. Do not edit; edit the files in",
    "-- supabase/migrations/ instead.",
    "--",
    "-- Paste this whole file into the Supabase SQL editor and run it once.",
    "-- BEGIN/COMMIT means a failure anywhere rolls the entire thing back, so you",
    "-- cannot end up with a half-applied schema.",
    "--",
    `-- Includes: ${PHASE1_MIGRATIONS.join(", ")}`,
    "--",
    "-- Two numbers are absent, retired rather than reused so that apply order",
    "-- stays equal to numeric order: 009 (cwl_signups, superseded by Phase 4B)",
    "-- and 012 (war_lineups, delivered by 024 instead). 012's file remains on",
    "-- disk as a comment-only tombstone and applies nothing.",
    "",
    "begin;",
    "",
  ];

  for (const file of PHASE1_MIGRATIONS) {
    const sql = readFileSync(join(DIR, "migrations", file), "utf8");
    parts.push(
      "-- " + "=".repeat(72),
      `-- ${file}`,
      "-- " + "=".repeat(72),
      "",
      sql.trimEnd(),
      "",
    );
  }

  parts.push(
    "commit;",
    "",
    "-- Verify from your terminal afterwards:  npm run supabase:check",
    "-- Expect: 21/21 tables returning zero rows to the anon key (T1.9).",
    "",
  );

  const out = join(DIR, "apply-all.sql");
  writeFileSync(out, parts.join("\n"), "utf8");

  console.log(`Wrote supabase/apply-all.sql — ${PHASE1_MIGRATIONS.length} migrations`);
  for (const f of PHASE1_MIGRATIONS) console.log(`  ${f}`);
  console.log("\nPaste it into the Supabase SQL editor and run once.");
}

main();
