// T11B.3 — game data: Town Hall caps, unit groups, and the ids the village
// export uses.
//
// The JSON beside this file is GENERATED by scripts/game-data.ts and must not be
// edited by hand — README.md says how to refresh it after a game update.
//
// Everything here is pure and has no Node or server imports, because the paste
// view (T11B.12) runs it in the browser.

import unitsFile from "./units.json";
import buildingsFile from "./buildings.json";
import type { ProgressUnit, Village } from "@/types/domain";

export type UnitGroup =
  | "hero"
  | "equipment"
  | "pet"
  | "elixirTroop"
  | "darkTroop"
  | "superTroop"
  | "siege"
  | "elixirSpell"
  | "darkSpell"
  | "guardian"
  | "builderTroop"
  | "builderHero";

export interface GameUnit {
  name: string;
  village: Village;
  group: UnitGroup;
  hero?: string;
  exportId: number;
  /** Max level at each hall level, index 0 = hall 1. 0 = not unlocked yet. */
  caps: number[];
}

export interface GameBuilding {
  exportId: number;
  name: string;
  village: Village;
  /** coc.py's building type — "Defense", "Resource", "Army", "Wall" … — or "trap". */
  kind: string;
  caps: number[];
  weaponCaps?: number[];
}

export const GAME_DATA_SOURCE = unitsFile.source;
export const HOME_HALLS: number = unitsFile.source.homeHalls;
export const BUILDER_HALLS: number = unitsFile.source.builderHalls;

const UNITS = unitsFile.units as GameUnit[];
const BUILDINGS = buildingsFile.buildings as GameBuilding[];

/** Name + village, because Baby Dragon exists in both and they are different units. */
const unitKey = (name: string, village: Village) => `${village}:${name}`;

const unitsByName = new Map(UNITS.map((u) => [unitKey(u.name, u.village), u]));
const unitsByExportId = new Map(UNITS.map((u) => [u.exportId, u]));
const buildingsByExportId = new Map(BUILDINGS.map((b) => [b.exportId, b]));

export function findUnit(name: string, village: Village): GameUnit | undefined {
  return unitsByName.get(unitKey(name, village));
}

export function unitByExportId(id: number): GameUnit | undefined {
  return unitsByExportId.get(id);
}

export function buildingByExportId(id: number): GameBuilding | undefined {
  return buildingsByExportId.get(id);
}

/** The cap at a hall level, or undefined when the data does not reach that level. */
export function capAt(caps: number[], hall: number | undefined): number | undefined {
  if (!hall || hall < 1) return undefined;
  return caps[hall - 1];
}

/** Display order and labels, shared by the sync-free page and the paste view. */
export const GROUP_ORDER: UnitGroup[] = [
  "hero",
  "equipment",
  "pet",
  "elixirTroop",
  "darkTroop",
  "siege",
  "elixirSpell",
  "darkSpell",
  "guardian",
  "superTroop",
  "builderHero",
  "builderTroop",
];

export const GROUP_LABELS: Record<UnitGroup, string> = {
  hero: "Heroes",
  equipment: "Hero equipment",
  pet: "Pets",
  elixirTroop: "Elixir troops",
  darkTroop: "Dark troops",
  superTroop: "Super troops",
  siege: "Siege machines",
  elixirSpell: "Elixir spells",
  darkSpell: "Dark spells",
  guardian: "Guardians",
  builderTroop: "Builder Base troops",
  builderHero: "Builder Base heroes",
};

/** Which API list a unit came from — the fallback when the data has never heard of it. */
export type UnitSource = "heroes" | "equipment" | "troops" | "spells";

/** A unit with its group and the cap that applies to THIS village. */
export interface ResolvedUnit extends ProgressUnit {
  group: UnitGroup;
  hero?: string;
  /** The cap for this Town Hall / Builder Hall, or the game maximum when unknown. */
  cap: number;
  /**
   * False when `cap` is the API's game maximum rather than a hall cap: the unit
   * is newer than the data, the hall level is unknown, or the player is ABOVE the
   * data's cap (which can only mean the data is stale). The page marks these so
   * a percentage is never presented as more certain than it is.
   */
  capKnown: boolean;
}

function fallbackGroup(source: UnitSource, village: Village): UnitGroup {
  if (village === "builder") return source === "heroes" ? "builderHero" : "builderTroop";
  switch (source) {
    case "heroes":
      return "hero";
    case "equipment":
      return "equipment";
    case "spells":
      return "elixirSpell";
    case "troops":
      return "elixirTroop";
  }
}

/**
 * Attach a group and the hall-relative cap to one unit from the API.
 *
 * `hall` is the Town Hall level for home units and the Builder Hall level for
 * builder units — the caller picks, because only the caller knows both.
 */
export function resolveUnit(
  unit: ProgressUnit,
  source: UnitSource,
  hall: number | undefined,
): ResolvedUnit {
  const data = findUnit(unit.name, unit.village);
  if (!data) {
    return {
      ...unit,
      group: fallbackGroup(source, unit.village),
      cap: unit.apiMax,
      capKnown: false,
    };
  }

  const cap = capAt(data.caps, hall);
  const trusted = cap !== undefined && unit.level <= cap;

  return {
    ...unit,
    group: data.group,
    ...(data.hero ? { hero: data.hero } : {}),
    cap: trusted ? cap : unit.apiMax,
    capKnown: trusted,
  };
}
