-- T6.8 — War lineup tables.
--
-- SUPERSEDED BY 024_war.sql. This file creates nothing and never did.
--
-- It was reserved for the war lineup tables and stayed comment-only until Phase
-- 6 landed. By then the task needed two things this number could not carry:
--
--   * war_members, the API's roster, which 003 never created and without which
--     the missed-attack list has no source (the same gap 019 filled for CWL)
--   * a write path for war_targets, which 006 left select-only
--
-- Splitting those across 012 and a later number would have meant applying 012
-- BEFORE 023 on a fresh database and AFTER it on this one, because 023 is
-- already applied. Numeric order and apply order would then disagree, which is
-- the one property that makes "never edit an applied migration" checkable.
--
-- So the whole of Phase 6's schema is in 024, and this number is retired the way
-- 009's was — see the note in test/pg-harness.ts.
--
-- Kept rather than deleted so the history reads honestly: a number that appears
-- in the tree in section 5 of IMPLEMENTATION.md, and in migrations.test.ts's
-- assertion that the bundle excludes comment-only stubs, should not simply
-- vanish. Nothing applies it and nothing should.
